backend:
  name: github
  repo: UNSW-Data-Soc/enchantment
  branch: edu-submissions

media_folder: "public/images/blog" # Location where files will be stored in the repo
public_folder: "/images/blog" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }